### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by lephino** [bboser/org.openhab.binding.nx584#1]
I'm having issues trying to get this binding to function.  If you setup the binding from the paperUI, it'll add the thing as nx584:nx584 which won't resolve to anything.  If I manually add the things and items, I don't get any update events from my panel.  Am I missing something?

openhab.log: 

`2017-04-28 04:00:32.303 [INFO ] [b.binding.nx584.handler.NX584Handler] - starting nx584 interface at port /dev/ttyUSB0 with baudrate 9600 and 22 zones
2017-04-28 04:00:32.342 [INFO ] [b.binding.nx584.internal.panel.NX584] - receiver started
2017-04-28 04:00:32.343 [ERROR] [b.binding.nx584.internal.panel.NX584] - receiver terminated unexpectedly
java.lang.NullPointerException
	at gnu.io.NRSerialPort.getInputStream(NRSerialPort.java:102)[209:com.neuronrobotics.nrjavaserial:3.12.0.OH]
	at org.openhab.binding.nx584.internal.panel.NX584$Receiver.run(NX584.java:206)[223:org.openhab.binding.nx584:2.0.0.201611192203]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2017-04-28 04:00:32.359 [INFO ] [b.binding.nx584.internal.panel.NX584] - transmitter started
2017-04-28 04:00:32.360 [ERROR] [b.binding.nx584.internal.panel.NX584] - cannot connect to security panel
java.lang.NullPointerException
	at gnu.io.NRSerialPort.getInputStream(NRSerialPort.java:102)[209:com.neuronrobotics.nrjavaserial:3.12.0.OH]
	at org.openhab.binding.nx584.internal.panel.NX584.connect(NX584.java:44)[223:org.openhab.binding.nx584:2.0.0.201611192203]
	at org.openhab.binding.nx584.handler.NX584Handler.initialize(NX584Handler.java:123)[223:org.openhab.binding.nx584:2.0.0.201611192203]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:708)[106:org.eclipse.smarthome.core.thing:0.9.0.201703201701]
	at org.eclipse.smarthome.core.thing.internal.ThingManager$9$1.call(ThingManager.java:1)[106:org.eclipse.smarthome.core.thing:0.9.0.201703201701]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181)[99:org.eclipse.smarthome.core:0.9.0.201703201701]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]
2017-04-28 04:00:32.362 [ERROR] [b.binding.nx584.internal.panel.NX584] - transmitter terminated unexpectedly`

I should also mention, I can screen /dev/ttyUSB0 and see heartbeats on the screen.

**Comment by lephino** [comment]
After a full reinstall, I was able to get this working (full reinstall of both the binding and openhab)
